# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class QrCli < Formula
  desc "Generate QR codes from the terminal"
  homepage "https://github.com/eliaseffects/qr-cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/eliaseffects/qr-cli/releases/download/v0.1.3/qr-cli_0.1.3_darwin_amd64.tar.gz"
      sha256 "33230c254c811e2a1c3443c98153066b4d59942152e91f0136e22c19b5cc6258"

      def install
        bin.install "qr"
      end
    end
    on_arm do
      url "https://github.com/eliaseffects/qr-cli/releases/download/v0.1.3/qr-cli_0.1.3_darwin_arm64.tar.gz"
      sha256 "2ae2c9370c0726ca8d0745dcd5259e82da4b6e2e4e3a115ccd972dcc9c1e8bf6"

      def install
        bin.install "qr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eliaseffects/qr-cli/releases/download/v0.1.3/qr-cli_0.1.3_linux_amd64.tar.gz"
        sha256 "23b95f32490cebb192e6256f4f515ba75dcc6f892a94c23cf56384733c63890b"

        def install
          bin.install "qr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eliaseffects/qr-cli/releases/download/v0.1.3/qr-cli_0.1.3_linux_arm64.tar.gz"
        sha256 "bbd98b1ea2405383c24520f87035ba8c81edf384f72894bd3ad07954e7510c8a"

        def install
          bin.install "qr"
        end
      end
    end
  end

  test do
    system "#{bin}/qr", "--version"
  end
end
